version: "3.9"

services:
  medcat-service:
    image: cogstacksystems/medcat-service:latest
    container_name: medcat-service
    ports:
      - "5000:5000"
    volumes:
      - ./models:/cat/models:rw
      - ./medcat-init.sh:/medcat-init.sh:ro
    entrypoint: ["/bin/bash", "/medcat-init.sh"]
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - APP_MODEL_CDB_PATH=/cat/models/medmen.cdb
      - APP_MODEL_VOCAB_PATH=/cat/models/vocab.dat
      - env-file=env/app.env \
      - env-file=env/medcat.env \
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/info"]
      interval: 30s
      timeout: 20s
      retries: 10
      start_period: 2m # Wait for the MedCATservice to be healthy before starting the fastapi-backend (adjust it based on your internet connection speed to download the medmen.cdb and vocab.dat files)

  fastapi-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    depends_on:
      medcat-service:
        condition: service_healthy

    environment:
      - MEDCAT_URL=http://medcat-service:5000/api/process
    volumes:
      - .:/app
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
